on:
  issues:
    types: [opened, edited]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Notifies the company about the issues
    steps:
      - name: Inform about interaction
        id: hello
        uses: RicardoPoleo/GitHubActionsTest
        with:
          company: ${{secrets.COMPANY}}
          rvrToken: ${{secrets.RVR_TOKEN}}
          room: ${{secrets.ROOM}}
